---
name: Docker push
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  push:
    if: ${{ github.repository != 'networkservicemesh/cmd-template' && (github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push') }}
    uses: NikitaSkrynnik/.github/.github/workflows/docker-push.yaml@test-docker-push
    secrets:
      docker-login: ${{ secrets.DOCKER_LOGIN }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
